### PR TITLE
Inclusion of Notion link for plan in repository

### PR DESCRIPTION
**Pull request by GeorgeHoneywood**

### CODE REVIEW

**Comment by JoeRourke123** [comment]
Hi Geroge. PuLL REQUEST REJECT!

**Comment by JoeRourke123** [comment]
Whoopsys sorrys here you go

**Comment by GeorgeHoneywood** [comment]
Thanks for merging my pull request :)

**Comment by GeorgeHoneywood** [comment]
@JoeRourke123 Please close this, I don't have perms.

**Pull request merged**
